ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - before: |
      export experiment="chess"  # Definindo a variável experiment como variável de ambiente
      if [ -z "$experiment" ]; then
        cd playground/1st-proof-of-concept
      else
        cd playground/$experiment
      fi
  command: |
    nvm install 13.3.0 && npm install && npm start


